package mfi.old_packages.toBeReviewedPkg.mfi.demoUtil;

import java.io.File;

import mfi.old_packages.toBeReviewedPkg.mfi.util.fileUtil.FileUtil;

public class DemoFileUtil {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("1-Creating a file:");
		String content = "This is a file generated by FileUtil.writeFileData() called from DemoFileUtil class\nYou can delete this file and run DemoFileUtil, it will be regenerated";
		
		String workingDirectory = FileUtil.getUserDirectory();
		String filePath = workingDirectory+"\\src\\main\\resources\\generated\\";
		
		String fileName = "DemoFileUtil.txt";
		FileUtil.writeFileData(content, filePath, fileName);
		
		File file = new File(filePath+fileName);
		if(file.exists()){
			System.out.println("File created successfully");
		}else{
			System.out.println("File NOT created:");
		}
		System.out.println();
		System.out.println("2-Reading the file");
		System.out.println(file.getAbsolutePath()+":\n"+FileUtil.readFileDataAsString(file));
	}

}
